services:
    trino:
        #    hostname: trino
        image: "trinodb/trino"
        ports:
            - "8088:8080"

        volumes:
            - type: bind
              source: ./presto/mysql/etc/catalog
              target: /etc/trino/catalog
